import { buildWindowsAgentHookPostCommand } from '../agent-hooks/installer-utils'
import {
  buildPosixHookPayloadCapture,
  buildPosixHookSpoolLines,
  buildWindowsHookEnvironmentGuardLines,
  buildWindowsHookStdinDrainEpilogue
} from '../agent-hooks/hook-stdin-contract'

export type CommandCodeManagedScriptTarget = 'local' | 'posix'

export function buildCommandCodeManagedScript(
  target: CommandCodeManagedScriptTarget = 'local'
): string {
  if (target === 'local' && process.platform === 'win32') {
    return [
      '@echo off',
      'setlocal',
      'if "%NIGHTSHIFT_AGENT_HOOK_PORT%"=="" if defined NIGHTSHIFT_AGENT_HOOK_ENDPOINT if exist "%NIGHTSHIFT_AGENT_HOOK_ENDPOINT%" call "%NIGHTSHIFT_AGENT_HOOK_ENDPOINT%" 2>nul',
      'if "%NIGHTSHIFT_AGENT_HOOK_TOKEN%"=="" if not "%NIGHTSHIFT_AGENT_HOOK_PORT%"=="" call :sourceEndpointByPort',
      ...buildWindowsHookEnvironmentGuardLines(),
      buildWindowsAgentHookPostCommand('command-code'),
      'exit /b 0',
      ':sourceEndpointByPort',
      'if not defined APPDATA exit /b 0',
      'if exist "%APPDATA%\\nightshift-dev\\agent-hooks" for /r "%APPDATA%\\nightshift-dev\\agent-hooks" %%F in (endpoint.cmd) do call :maybeSourceEndpoint "%%~fF"',
      'if "%NIGHTSHIFT_AGENT_HOOK_TOKEN%"=="" if exist "%APPDATA%\\nightshift\\agent-hooks" for /r "%APPDATA%\\nightshift\\agent-hooks" %%F in (endpoint.cmd) do call :maybeSourceEndpoint "%%~fF"',
      'exit /b 0',
      ':maybeSourceEndpoint',
      'if not "%NIGHTSHIFT_AGENT_HOOK_TOKEN%"=="" exit /b 0',
      'for /f "tokens=2 delims==" %%P in (\'findstr /b /c:"set NIGHTSHIFT_AGENT_HOOK_PORT=" "%~1" 2^>nul\') do if "%%P"=="%NIGHTSHIFT_AGENT_HOOK_PORT%" call "%~1" 2>nul',
      'exit /b 0',
      ...buildWindowsHookStdinDrainEpilogue(),
      ''
    ].join('\r\n')
  }

  return [
    '#!/bin/sh',
    ...buildPosixHookPayloadCapture(),
    ...buildPosixHookSpoolLines('command-code'),
    '__nightshift_read_ancestor_var() {',
    '  __nightshift_name="$1"',
    '  __nightshift_pid="${PPID:-}"',
    '  while [ -n "$__nightshift_pid" ] && [ "$__nightshift_pid" != "0" ] && [ "$__nightshift_pid" != "1" ]; do',
    '    __nightshift_value=""',
    '    if [ -r "/proc/$__nightshift_pid/environ" ]; then',
    '      __nightshift_value=$(tr "\\000" "\\n" < "/proc/$__nightshift_pid/environ" 2>/dev/null | sed -n "s/^${__nightshift_name}=//p" | head -n 1)',
    '    fi',
    '    if [ -z "$__nightshift_value" ]; then',
    '      __nightshift_value=$(ps eww -p "$__nightshift_pid" -o command= 2>/dev/null | tr " " "\\n" | sed -n "s/^${__nightshift_name}=//p" | head -n 1)',
    '    fi',
    '    if [ -n "$__nightshift_value" ]; then',
    '      printf "%s\\n" "$__nightshift_value"',
    '      return 0',
    '    fi',
    '    __nightshift_pid=$(ps -o ppid= -p "$__nightshift_pid" 2>/dev/null | tr -d " ")',
    '  done',
    '  return 1',
    '}',
    '__nightshift_fill_from_ancestor() {',
    '  __nightshift_name="$1"',
    '  case "$__nightshift_name" in',
    '    NIGHTSHIFT_AGENT_HOOK_ENDPOINT) [ -z "${NIGHTSHIFT_AGENT_HOOK_ENDPOINT:-}" ] || return 0 ;;',
    '    NIGHTSHIFT_AGENT_HOOK_PORT) [ -z "${NIGHTSHIFT_AGENT_HOOK_PORT:-}" ] || return 0 ;;',
    '    NIGHTSHIFT_AGENT_HOOK_TOKEN) [ -z "${NIGHTSHIFT_AGENT_HOOK_TOKEN:-}" ] || return 0 ;;',
    '    NIGHTSHIFT_AGENT_HOOK_ENV) [ -z "${NIGHTSHIFT_AGENT_HOOK_ENV:-}" ] || return 0 ;;',
    '    NIGHTSHIFT_AGENT_HOOK_VERSION) [ -z "${NIGHTSHIFT_AGENT_HOOK_VERSION:-}" ] || return 0 ;;',
    '    NIGHTSHIFT_PANE_KEY) [ -z "${NIGHTSHIFT_PANE_KEY:-}" ] || return 0 ;;',
    '    NIGHTSHIFT_TAB_ID) [ -z "${NIGHTSHIFT_TAB_ID:-}" ] || return 0 ;;',
    '    NIGHTSHIFT_WORKTREE_ID) [ -z "${NIGHTSHIFT_WORKTREE_ID:-}" ] || return 0 ;;',
    '    NIGHTSHIFT_AGENT_LAUNCH_TOKEN) [ -z "${NIGHTSHIFT_AGENT_LAUNCH_TOKEN:-}" ] || return 0 ;;',
    '    *) return 0 ;;',
    '  esac',
    '  __nightshift_value=$(__nightshift_read_ancestor_var "$__nightshift_name") || return 0',
    '  [ -n "$__nightshift_value" ] && export "$__nightshift_name=$__nightshift_value"',
    '}',
    '__nightshift_endpoint_value() {',
    '  __nightshift_endpoint_name="$1"',
    '  __nightshift_endpoint_path="$2"',
    '  sed -n "s/^${__nightshift_endpoint_name}=//p" "$__nightshift_endpoint_path" 2>/dev/null | head -n 1',
    '}',
    '__nightshift_fill_from_endpoint_file() {',
    '  __nightshift_endpoint_path="$1"',
    '  [ -r "$__nightshift_endpoint_path" ] || return 0',
    '  __nightshift_endpoint_port=$(__nightshift_endpoint_value NIGHTSHIFT_AGENT_HOOK_PORT "$__nightshift_endpoint_path")',
    '  if [ -n "${NIGHTSHIFT_AGENT_HOOK_PORT:-}" ] && [ -n "$__nightshift_endpoint_port" ] && [ "$__nightshift_endpoint_port" != "$NIGHTSHIFT_AGENT_HOOK_PORT" ]; then',
    '    return 0',
    '  fi',
    '  for __nightshift_endpoint_name in NIGHTSHIFT_AGENT_HOOK_PORT NIGHTSHIFT_AGENT_HOOK_TOKEN NIGHTSHIFT_AGENT_HOOK_ENV NIGHTSHIFT_AGENT_HOOK_VERSION; do',
    '    eval "__nightshift_current=\\${$__nightshift_endpoint_name:-}"',
    '    [ -z "$__nightshift_current" ] || continue',
    '    __nightshift_endpoint_value=$(__nightshift_endpoint_value "$__nightshift_endpoint_name" "$__nightshift_endpoint_path")',
    '    [ -n "$__nightshift_endpoint_value" ] && export "$__nightshift_endpoint_name=$__nightshift_endpoint_value"',
    '  done',
    '}',
    '# Why: Command Code sanitizes hook subprocess env. The parent TUI process',
    '# still has Nightshift pane/hook metadata, so recover it before posting.',
    'for __nightshift_name in NIGHTSHIFT_AGENT_HOOK_ENDPOINT NIGHTSHIFT_AGENT_HOOK_PORT NIGHTSHIFT_AGENT_HOOK_TOKEN NIGHTSHIFT_AGENT_HOOK_ENV NIGHTSHIFT_AGENT_HOOK_VERSION NIGHTSHIFT_PANE_KEY NIGHTSHIFT_TAB_ID NIGHTSHIFT_WORKTREE_ID NIGHTSHIFT_AGENT_LAUNCH_TOKEN; do',
    '  __nightshift_fill_from_ancestor "$__nightshift_name"',
    'done',
    'if [ -n "$NIGHTSHIFT_AGENT_HOOK_ENDPOINT" ] && [ -r "$NIGHTSHIFT_AGENT_HOOK_ENDPOINT" ]; then',
    '  __nightshift_fill_from_endpoint_file "$NIGHTSHIFT_AGENT_HOOK_ENDPOINT"',
    'fi',
    '# Why: Command Code strips TOKEN-like env vars before invoking hooks. If',
    '# NIGHTSHIFT_AGENT_HOOK_ENDPOINT was not exported into this PTY, recover the',
    '# matching endpoint file by the unstripped loopback port.',
    'if [ -z "$NIGHTSHIFT_AGENT_HOOK_TOKEN" ] && [ -n "$NIGHTSHIFT_AGENT_HOOK_PORT" ]; then',
    '  for endpoint in \\',
    '    "$HOME/Library/Application Support/nightshift-dev/agent-hooks"/*/endpoint.env \\',
    '    "$HOME/Library/Application Support/nightshift-dev/agent-hooks/endpoint.env" \\',
    '    "${XDG_CONFIG_HOME:-$HOME/.config}/nightshift-dev/agent-hooks"/*/endpoint.env \\',
    '    "${XDG_CONFIG_HOME:-$HOME/.config}/nightshift-dev/agent-hooks/endpoint.env" \\',
    '    "$HOME/Library/Application Support/nightshift/agent-hooks/endpoint.env" \\',
    '    "${XDG_CONFIG_HOME:-$HOME/.config}/nightshift/agent-hooks/endpoint.env"; do',
    '    [ -r "$endpoint" ] || continue',
    '    endpoint_port=$(sed -n "s/^NIGHTSHIFT_AGENT_HOOK_PORT=//p" "$endpoint" | head -n 1)',
    '    if [ "$endpoint_port" = "$NIGHTSHIFT_AGENT_HOOK_PORT" ]; then',
    '      __nightshift_fill_from_endpoint_file "$endpoint"',
    '      break',
    '    fi',
    '  done',
    'fi',
    'if [ -z "$NIGHTSHIFT_AGENT_HOOK_PORT" ] || [ -z "$NIGHTSHIFT_AGENT_HOOK_TOKEN" ] || [ -z "$NIGHTSHIFT_PANE_KEY" ]; then',
    '  spool_hook_event',
    '  exit 0',
    'fi',
    // Timeout caps best-effort hook posts if the local listener stalls.
    // Why: pipe payload to curl's stdin (`payload@-`) instead of an inline
    // `payload=$VALUE` arg, so tens-of-KB tool output stays off the curl
    // command line (EDR command-line false positives). Wire body is identical.
    'printf \'%s\' "$payload" | curl -sS -X POST "http://127.0.0.1:${NIGHTSHIFT_AGENT_HOOK_PORT}/hook/command-code" \\',
    '  --connect-timeout 0.5 --max-time 1.5 \\',
    '  -H "Content-Type: application/x-www-form-urlencoded" \\',
    '  -H "X-Nightshift-Agent-Hook-Token: ${NIGHTSHIFT_AGENT_HOOK_TOKEN}" \\',
    '  --data-urlencode "paneKey=${NIGHTSHIFT_PANE_KEY}" \\',
    '  --data-urlencode "tabId=${NIGHTSHIFT_TAB_ID}" \\',
    '  --data-urlencode "launchToken=${NIGHTSHIFT_AGENT_LAUNCH_TOKEN}" \\',
    '  --data-urlencode "worktreeId=${NIGHTSHIFT_WORKTREE_ID}" \\',
    '  --data-urlencode "env=${NIGHTSHIFT_AGENT_HOOK_ENV}" \\',
    '  --data-urlencode "version=${NIGHTSHIFT_AGENT_HOOK_VERSION}" \\',
    '  --data-urlencode "payload@-" >/dev/null 2>&1 || spool_hook_event',
    'exit 0',
    ''
  ].join('\n')
}
